server:
  port: 7970
spring:
  application:
    name: tx-manager
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/tx-manager?serverTimezone=GMT%2B8&useUnicode=true&characterEncodeing=utf-8&useSSL=false
      username: root
      password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update

  redis:
    host: localhost
    port: 6379
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

logging:
  level:
    #分布式事务日志
    com.codingapi.txlcn: DEBUG
